export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const FETCH_AUTH = "FETCH_AUTH";
export const FETCH_AUTH_ERROR = "FETCH_AUTH_ERROR";
export const FETCH_AUTH_SUCCESS = "FETCH_AUTH_SUCCESS";

export const FETCH_TABLE = "FETCH_TABLE";
export const FETCH_TABLE_ERROR = "FETCH_TABLE_ERROR";
export const FETCH_TABLE_SUCCESS = "FETCH_TABLE_SUCCESS";
export const SET_TABLE_DATA = "SET_TABLE_DATA";
export const SET_DIALOG_CREATE_OPEN = "SET_DIALOG_CREATE_OPEN";
